clients/cli/README.md, clients/cli/src/prover.rs, public/install.sh
=> fix: Terms

proto/orchestrator.proto
Hyperlink to the correct place.
=> docs: Update terms link

clients/cli/README.md
=> docs: Update README.md install instructions

CONTRIBUTING.md, clients/cli/Cargo.toml, clients/cli/README.md
=> docs: Update installation instructions

.github/workflows/ci.yml, clients/cli/Cargo.lock, clients/cli/Cargo.toml, clients/cli/src/analytics.rs, clients/cli/src/config.rs, clients/cli/src/prover.rs, proto/generate_protobufs.sh
=> ci: automatically lint and build CLI

clients/cli/build.rs, clients/cli/src/analytics.rs
This PR replaces some `unwrap()` calls with improved error handling using match and others.
=> feat:remove unwraps

clients/cli/src/prover.rs
This PR merges some changes to `staging` branch.
It generates the inputs in the client CLI.
=> remove old code for inputs and create new code for creating the inputs

README.md
Update README's description to match current structure
=> docs: Update repo structure

CONTRIBUTING.md, README.md
=> docs: Update CONTRIBUTING.md to reference new repo and fix broken link

public/install.sh
- Instead of getting main, check out the latest tag when running install.sh
- List the full command when explaining how to use NONINTERACTIVE
=> feat: check out latest tag

public/install.sh
Add quotes - I had meant to include this in https://github.com/nexus-xyz/network-api/pull/63
=> fix: add missing quotes

clients/cli/Cargo.lock, clients/cli/Cargo.toml, clients/cli/src/utils/experiment.rs, clients/cli/src/utils/mod.rs, clients/cli/src/utils/prover.rs
Determine experiment enrollment using md5 hashing and salt for compatibility with web.
=> feat: default program using md5 hashing

README.md, public/install.sh
Testnet is over. Install script now points to devnet.
=> feat: update CLi copy for testnet sunset

README.md, public/install.sh
This PR updates the readme and the CLI opener:
=> feat: update CLI and README copy

CONTRIBUTING.md, LICENSE-APACHE, clients/cli/src/generated/nexus.orchestrator.rs, clients/cli/src/prover.rs, tests/test_updater.sh
Fixed errors and inaccuracies in the project's textual materials. Improved readability of texts and documentation
=> Fixed minor typos

.github/ISSUE_TEMPLATE/bug_report.md, .github/ISSUE_TEMPLATE/config.yml
=> docs: Add issue template

README.md, clients/cli/Cargo.lock, clients/cli/Cargo.toml, clients/cli/src/utils/cli_branding.rs, public/install.sh
the install script has a bug where the user is not being prompted for input when using the `curl` command. This fixes this.
=> fix: install script

clients/cli/Cargo.lock, clients/cli/Cargo.toml, clients/cli/src/main.rs, clients/cli/src/orchestrator_client.rs, clients/cli/src/setup.rs, clients/cli/src/utils/cli_branding.rs
Updated error logging for connecting to the server to have more helpful messages
=> feat: updated error 

README.md, clients/cli/src/setup.rs, public/install.sh
Copy updates post Testnet II sunset.
=> feat: copy updates

clients/cli/Cargo.lock, clients/cli/Cargo.toml
Removes a number of unused dependencies.
fixes: NET-955
=> chore: Remove unused Cargo dependencies

README.md
The program should be started using the subcommand.
```
./target/release/nexus-network start --env beta
```
=> docs: Update startup parameters

README.md
Noticed that "few" in this context sounded a bit off, so I replaced it with "several" for better readability.
=> docs: fix incorrect plural form in UI text

README.md, public/install.sh
- The node id file name changed, so install.sh needs to updated to match
- Update docs for node id
=> fix: Update install.sh to check for config.json

public/install.sh
Update path to node id config in comment
=> docs: Update install.sh file path

README.md, clients/cli/src/utils/cli_branding.rs
chore: Change the banner that displays on startup to reflect new name and simplified graphic
docs: Update README title.
=> change: update branding

clients/cli/Cargo.toml, clients/cli/examples/src/main.rs, clients/cli/src/flops.rs, clients/cli/src/main.rs, clients/cli/src/prover.rs, clients/cli/src/setup.rs
Spawns multiple prover threads that run in parallel. The default is 1 thread, but a larger number can be specified via the --max-threads option.
=> feat: Basic parallel proving

clients/cli/Cargo.lock, clients/cli/Cargo.toml, clients/cli/Dockerfile
Creates a Dockerfile for the CLI
Fixes: https://linear.app/nexus-labs/issue/NET-492/cli-dockerfile
=> feat: Dockerfile

.github/workflows/release.yml, clients/cli/Cargo.lock, clients/cli/Cargo.toml
Updates the release workflow to build for Linux (ARM64, x86_64), MacOS (ARM64, MacOS), and Windows targets, and include them as release artifacts
=> ci: Release workflow builds cross-platform binaries

clients/cli/src/prover.rs
=> chore: Remove unused prover functions

clients/cli/src/analytics.rs, clients/cli/src/environment.rs
=> remove dev environment

clients/cli/src/ui/dashboard.rs, clients/cli/src/ui/mod.rs
Restores the unicode symbols to the log lines shown in the Dashboard screen. These got lost in the change to support logging to console
=> ui: Restore icons to logs in dashboard

clients/cli/src/analytics.rs, clients/cli/src/main.rs, clients/cli/src/prover.rs, clients/cli/src/prover_runtime.rs
Adds analytics events on submitting proofs
=> feat: Send analytics

clients/cli/src/prover_runtime.rs
```rust
// OLD APPROACH - Time-driven polling
loop {
tokio::select! {
// Every 100ms: Get ONE new task
_ = tokio::time::sleep(100ms), if !fetch_existing_tasks => {
orchestrator.get_proof_task() // Single task
}
// Every 3000ms: Get ALL existing assigned tasks
_ = tokio::time::sleep(3000ms), if fetch_existing_tasks => {
orchestrator.get_tasks() // All assigned tasks
}
}
}
```
Problems:
- Constantly polling every 100ms/3000ms
- Fetches tasks even when queue is full
- Many unnecessary API calls
- Gets tasks one-by-one when queue is empty
```rust
// NEW APPROACH - Queue-driven batching
loop {
tokio::select! {
// Every 500ms: Check if queue needs refilling
_ = tokio::time::sleep(500ms) => {
let tasks_in_queue = TASK_QUEUE_SIZE - sender.capacity();
// Only fetch if queue is low (< 5 tasks)
if …
```
=> Add Queue-driven batching

clients/cli/Cargo.lock, clients/cli/Cargo.toml
=> Update to 0.8.14

clients/cli/src/orchestrator/client.rs
Summary:
Avoid the repeate pattern in Client.
Test Plan:
Summary:
Test Plan:
---
Stack created with [Sapling](https://sapling-scm.com). Best reviewed with [ReviewStack](https://reviewstack.dev/nexus-xyz/nexus-cli/pull/1627).
* #1643
* #1645
* __->__ #1627
=> DRY protobuf POST/GET

.github/workflows/firebase-hosting-release.yml
Update the Firebase site for cli.nexus.xyz on pushing a tag.
=> ci: Deploy on tag

clients/cli/src/system.rs
=> Clean up old println

clients/cli/Cargo.lock, clients/cli/Cargo.toml, clients/cli/src/ui/dashboard.rs, clients/cli/src/workers/online.rs
Summary:
Test Plan:
---
Stack created with [Sapling](https://sapling-scm.com). Best reviewed with [ReviewStack](https://reviewstack.dev/nexus-xyz/nexus-cli/pull/1669).
* __->__ #1669
* #1668
=> Release v0.8.18

README.md
Enhances community visibility by adding Discord badge alongside existing social link
=> docs: Add Discord community badge

clients/cli/src/orchestrator/client.rs
- Use the new endpoint for getting tasks
- Eliminate payload bodies from GET requests
=> chore: Remove payload bodies from GET requests

clients/cli/Cargo.lock, clients/cli/Cargo.toml, clients/cli/src/events.rs, clients/cli/src/main.rs, clients/cli/src/prover_runtime.rs, clients/cli/src/ui/dashboard.rs, clients/cli/src/version_checker.rs
Summary:
- Auto check for new version at start up, and afte every 24 hours.
=> Add periodic version update checking to dashboard

clients/cli/Cargo.lock, clients/cli/Cargo.toml, clients/cli/src/error_classifier.rs, clients/cli/src/prover.rs, clients/cli/src/workers/offline.rs
Summary:
Test Plan:
---
Stack created with [Sapling](https://sapling-scm.com). Best reviewed with [ReviewStack](https://reviewstack.dev/nexus-xyz/nexus-cli/pull/1685).
* __->__ #1685
* #1684
=> Release v0.9.2

clients/cli/src/ui/dashboard.rs, clients/cli/src/workers/offline.rs, clients/cli/src/workers/online.rs
Summary:
By wrapping the `Line` inside `Paragraph`, we use `.wrap()` method to render the line.
This will fix overflow problem.
Test Plan:
---
Stack created with [Sapling](https://sapling-scm.com). Best reviewed with [ReviewStack](https://reviewstack.dev/nexus-xyz/nexus-cli/pull/1700).
* #1701
* __->__ #1700
=> Fix line overflow

clients/cli/Cargo.lock, clients/cli/Cargo.toml, clients/cli/src/ui/dashboard.rs, clients/cli/src/workers/offline.rs, clients/cli/src/workers/online.rs
Summary:
Test Plan:
---
Stack created with [Sapling](https://sapling-scm.com). Best reviewed with [ReviewStack](https://reviewstack.dev/nexus-xyz/nexus-cli/pull/1701).
* __->__ #1701
* #1700
=> v0.9.6 Release

clients/cli/src/analytics.rs, clients/cli/src/workers/offline.rs
Support for multiple events on proving. proof_node is shared with web
=> feat: analytics event id

clients/cli/Cargo.lock, clients/cli/Cargo.toml, clients/cli/src/main.rs, clients/cli/src/orchestrator/client.rs, clients/cli/src/orchestrator/mod.rs, clients/cli/src/proto/nexus.orchestrator.rs, clients/cli/tests/cli.rs, proto/orchestrator.proto
Adds a new orchestrator API for getting node wallet address
=> feat: Get node wallet address from orchestrator to use as analytics id

public/install.sh
The issue was that curl was being piped directly to awk, which could cause timing problems when the API request doesn't complete properly.
The script is now much more reliable and will give clear feedback if there are network issues or API problems, rather than silently failing with an empty URL. This should resolve the intermittent issues you were experiencing.
=> Fix Install.sh race condition

public/install.sh
As I'm testing installation on my docker, I found the previous URL parsing does not work properly.
This PR improves URL parsing, work in my case.
=> Improve URL parsing

README.md
Move program submission instructions to a different step
Pure docs change
=> docs: Update README.md program submission

clients/cli/src/consts.rs, clients/cli/src/orchestrator/error.rs, clients/cli/src/register.rs, clients/cli/src/workers/online.rs
=> Adjust backoff time limit according `retry-after`

clients/cli/src/orchestrator/client.rs, clients/cli/src/orchestrator/mod.rs, clients/cli/src/proto/nexus.orchestrator.rs, clients/cli/src/task.rs, clients/cli/src/workers/online.rs, proto/orchestrator.proto
Update proto interface to support hash-only proofs.
Implement checking the proto interface
Add support for max task difficulty (not implemented yet)
=> feat: support for hash-only proofs

clients/cli/src/main.rs
=> Restore anonymous prover

clients/cli/src/consts.rs, clients/cli/src/events.rs, clients/cli/src/ui/dashboard.rs, clients/cli/src/workers/offline.rs, clients/cli/src/workers/online.rs
feat: improve dashboard UX with simplified messaging
- Add Waiting event type with ⏳ emoji for better status indication
- Remove technical "step X of 3" messaging pattern
- Simplify proof computation messages to "Computing...", "Requesting task...", "Submitting..."
- Remove worker type labels from dashboard for cleaner UI
- Use Waiting event type instead of Error for rate limiting scenarios
- Streamline final success message to "Submitted! ≈300 points will be added soon"
These changes make the interface more user-friendly by replacing technical
language with clear, actionable status messages.
=> feat: improve dashboard UX with simplified messaging

clients/cli/src/consts.rs, clients/cli/src/workers/online.rs
Summary:
Test Plan:
---
Stack created with [Sapling](https://sapling-scm.com). Best reviewed with [ReviewStack](https://reviewstack.dev/nexus-xyz/nexus-cli/pull/1875).
* #1876
* __->__ #1875
=> Add fetch task delay timer

clients/cli/Cargo.lock, clients/cli/Cargo.toml
=> Release 0.10.3

clients/cli/src/version_requirements.rs, firebase.json, functions/.gitignore, functions/README.md, functions/deploy.sh, functions/package-lock.json, functions/package.json, functions/src/index.ts, functions/tsconfig.json
Node operators were experiencing rate limiting when fetching `version.json` from Firebase Hosting, causing version requirement checks to fail and preventing CLI startup.
Implemented a 3-tier fallback system with a Cloud Function cache to eliminate rate limiting issues while maintaining low hosting costs:
1. **Primary**: `https://cli.nexus.xyz/version.json` (Firebase Hosting)
2. **Cache**: `https://us-central1-nexus-cli.cloudfunctions.net/version` (Cloud Function)  
3. **Fallback**: GitHub raw URL (ultimate fallback)
- **`clients/cli/src/version_requirements.rs`**: Updated version fetching logic to try all three endpoints with comprehensive error reporting
- **`functions/`**: New Firebase Cloud Function that caches `version.json` responses
- Respects origin's `Cache-Control: max-age=3600` …
=> feat: cloud function version cache

clients/cli/src/analytics.rs, clients/cli/src/main.rs
defensive coding to avoid a situation where orchestrator inputs could cause a panic in analytics
=> fix: analytics panic

clients/cli/scripts/build_guest.sh, clients/cli/scripts/peak_memory.sh, tests/test_updater.sh
=> Format shell script

clients/cli/src/main.rs
=> Fix wrong description

clients/cli/src/consts.rs, clients/cli/src/session/tui_mode.rs, clients/cli/src/ui/app.rs, clients/cli/src/ui/dashboard/components/header.rs, clients/cli/src/ui/dashboard/components/logs.rs, clients/cli/src/ui/dashboard/state.rs, clients/cli/src/ui/dashboard/updaters.rs, clients/cli/src/workers/authenticated_worker.rs
Summary:
This is a final fix to resolve TUI freeze at 17 tasks.
Test Plan:
---
Stack created with [Sapling](https://sapling-scm.com). Best reviewed with [ReviewStack](https://reviewstack.dev/nexus-xyz/nexus-cli/pull/1926).
* #1932
* __->__ #1926
=> Fix TUI display issues

clients/cli/Cargo.lock, clients/cli/Cargo.toml
=> Release 0.10.8

clients/cli/src/network/client.rs, clients/cli/src/orchestrator/client.rs, clients/cli/src/orchestrator/mod.rs, clients/cli/src/prover/handlers.rs, clients/cli/src/prover/pipeline.rs, clients/cli/src/prover/types.rs, clients/cli/src/workers/prover.rs, clients/cli/src/workers/submitter.rs
Proto now has a field supporting multiple-input proving tasks. We need to populate it for PROOF_REQUIRED tasks.
Includes unit test
=> feat: populate proofs field

clients/cli/src/task.rs
Add specific hash values as computed by server's library.
=> Make tests a bit stronger

clients/cli/src/analytics.rs, clients/cli/src/runtime.rs, clients/cli/src/session/setup.rs, clients/cli/src/workers/core.rs, clients/cli/src/workers/submitter.rs
Ping a cloud function endpoint when proofs are successful so we can ensure that the address gets credit for daily proving.
=> feat: report proving

README.md, clients/cli/src/main.rs, clients/cli/src/network/client.rs, clients/cli/src/orchestrator/client.rs, clients/cli/src/orchestrator/mod.rs, clients/cli/src/proto/nexus.orchestrator.rs, clients/cli/src/runtime.rs, clients/cli/src/session/setup.rs, clients/cli/src/workers/authenticated_worker.rs, clients/cli/src/workers/core.rs, clients/cli/src/workers/fetcher.rs, proto/orchestrator.proto
This PR implements an adaptive difficulty promotion system with input validation that balances performance optimization with safety and user control. The system is designed to:
- ✅ Automatically optimize task difficulty based on performance
- ✅ Respect user-specified limits and overrides
- ✅ Provide safe defaults that won't overwhelm nodes
- ✅ Include comprehensive testing to prevent regressions
- ✅ Validate all inputs to prevent user errors
- ✅ Maintain backward compatibility where possible
- ✅ Provide clear error messages for invalid input
**New Promotion Path:**
- **Default Start**: `SmallMedium` difficulty (appropriate for CLI users)
- **Promotion Path**: `SmallMedium` → `Medium` → `Large`
- **Promotion Limit**: Stops at `Large` (no automatic promotion to `ExtraLarge`)
- **Time …
=> feat: self-regulating difficulty and command line override

clients/cli/src/workers/authenticated_worker.rs
1.  `start_time` is recorded before obtaining the task. If a rate limit is received from the backend, it will wait for it, causing `duration_secs` to include the waiting time from the backend. This will not accurately reflect the actual execution time of the task, affecting the judgment of the difficulty of subsequent tasks.
2. `difficulty` using `as_str_name()`
3. According to PR #1987  `last_success_difficulty` will be replaced by returning the actual difficulty of the task, so `Difficulty` is printed instead of `Request Difficulty`. If `task` instances contain difficulty values ​​in the future, `task.difficulty` should be used instead.
Thanks to Vau from discord for comments and suggestions
=> fix: 'duration_secs' contains the waiting time

clients/cli/src/main.rs, clients/cli/src/network/client.rs, clients/cli/src/orchestrator/client.rs, clients/cli/src/orchestrator/mod.rs, clients/cli/src/proto/nexus.orchestrator.rs, clients/cli/src/task.rs, clients/cli/src/workers/fetcher.rs, proto/orchestrator.proto
The client-side auto-promotion logic had a limitation where it would track successes using the *requested* difficulty rather than the *actual* difficulty received from the server. This caused issues because:
1. Client requests `Large` difficulty
2. Server provides `SmallMedium` task (due to reputation-based gating)
3. Client tracks success as `Large` difficulty (using requested difficulty)
4. Next promotion tries to go from `Large` to `ExtraLarge`
5. Server still provides `SmallMedium` task (reputation hasn't improved)
This created a mismatch where the client could get promoted past its level of ability.
Updated the protobuf definition to include the actual task difficulty in the server response, allowing clients to track promotions based on what they actually received rather than what …
=> feat: add task difficulty to GetProofTaskResponse

clients/cli/src/main.rs, clients/cli/src/proto/nexus.orchestrator.rs, clients/cli/src/workers/fetcher.rs, proto/orchestrator.proto
Add EXTRA_LARGE_3, EXTRA_LARGE_4, EXTRA_LARGE_5
=> feat: Add more difficulty levels
