public/install.sh

Use https: instead of git: for the clone command

use https instead of git

---

clients/cli/src/prover.rs

The line 286 "duration"  is not complete the program time. If the customer's network is not very good,  post the result of proof will take more time, so proof_cycles_hertz and proof_cycles_per_minute  will not be the real value.

fix: Hz of proved Program  

---

clients/cli/src/config.rs
clients/cli/src/prover.rs

feat: increase precision of proving speed, release-only analytics

---

clients/cli/Cargo.toml
clients/cli/src/prover.rs

Live network stats are offline as we prepare for the next beta.
Aggregate network stats from the current beta are available in the [retrospective blog post](https://blog.nexus.xyz/next-steps-for-nexus-network-beta/
).

chore: remove beta stats link

---

clients/cli/README.md

Clarify that email saving is a web-only feature (for now).

docs: Known issue for linking email

---

clients/cli/src/config.rs

In preparation for moving to Firebase Analytics, disable tracking.

chore: Don't send analytics during devnet

---

clients/cli/Cargo.lock
clients/cli/src/analytics.rs
clients/cli/src/config.rs

**Things to note:**
1. the `config.rs` file had some slight refactoring to make thing simpler to read (using enums, comments, etc...)
2. replacing mixpanel with Firebase, but not regular firebase, but the measurement protocol
3. Updated `analytics.rs` so that it has the payload stricture that firebase expects
**Why the measurement protocol?**
For tracking events, this PR uses the Firebase Measurement Protocol.
Firebase is mostly designed for mobile and web apps, but for our use case of a CLI, we can use the Measurement Protocol to track events by POST to a URL. 
Firebase format for properties for [Measurement protocol](https://developers.google.com/analytics/devguides/collection/protocol/ga4/reference?client_type=firebase#payload
)

feat: use firebase instead of mixpanel in for event tracking

---

public/install.sh

fix: git pull error and remembering terms

---

clients/cli/src/generated/nexus.orchestrator.rs
clients/cli/src/prover.rs
proto/orchestrator.proto

this removes `network` from the protobuf for `ClientProgramProofRequest`

fix: remove network key from protobuf

---

README.md
clients/cli/src/prover.rs
public/install.sh

If this CLI instance doesn't already have a web prover id, ask for the web prover id on startup.
This has to be in install.sh because it reads in input and is in a pipe to sh command.
**Steps to test**
1. cd into your checkout of network-api.
2. git checkout collinjackson/set-cli-client-id
3. cat ./public/install.sh | sh

feat: Prompt to set prover id

---

clients/cli/src/utils/updater.rs

the updater's production version has the wrong remote repo it pulls from. This fixes that.
it should be pulling form `https://github.com/nexus-xyz/network-api.git` (this repo), but it was pulling from another one.

fix: auto-updater is pulling from wrong remote 

---

clients/cli/src/updater.rs
clients/cli/src/utils/updater.rs

This PR does two things:
1. There is an error in the `updater.rs` that is red and scary, but is actually harmless (at this stage). This PR changes the color so it seems more representative.
2. The updater currently runs every 5 minutes (this was the intent for the 1st day so we can observe). The long-running intent is to have it run every hour. So the PR updates the time to 1 hour (the long-running intent).

hotfix: update error logging of the updater error

---

clients/cli/Cargo.lock
clients/cli/Cargo.toml
clients/cli/src/prover.rs
clients/cli/src/updater.rs
clients/cli/src/utils/prover.rs
clients/cli/src/utils/updater.rs

This PR does a few things:
- when a user gets a prover-id, it is used to determine what program they should use for proving.
This is done by doing the following:
- make a hash of the prover id 
- modulo the hash by 100
- if the resulting number is beneath the threshold, then it chooses the cancer diagnostic program
- remove the updater for now
- bump version number in cargo <-- old chore

feat: make default program sticky

---

public/install.sh

Users were not seeing the instructions for the prover ID. This CLI adds some copy and format changes to the install script. See below:

feat: add highlighting in the install script

---

clients/cli/src/prover.rs

The `program_name` property has been added to the following tracking events:
1. `progress`
2. `close_error`
3. `disconnect`
i added to the other two in case there is some reason a program may lead to more disconnects or errors, we could quickly identify them

feat: client side tracking of the program name

---

clients/cli/src/prover.rs
clients/cli/src/prover_id_manager.rs

The CLI wasn't saving autogenerated prover IDs in certain error cases. When reading the prover ID file failed, some error paths didn't properly handle saving the default ID.
- Refactored `get_or_generate_prover_id` to handle some missing cases (e.g. hitting an error, missing file, etc...)
- Since there are a few cases, refactored the function into smaller functions that are used by the particular case (or re-used as appropriater)
- Simplified error handling to ensure consistent behavior
- Added test coverage for empty file scenarios
- Moved a print statement so `Your current prover identifier is` shows up in the `Setting up CLI configuration.` section (see image below). Before this PR, the prover id was logged in same section as the web socket connection. This was misleading.

fix: fix writing prover-id to file and reading it

---

clients/cli/src/prover.rs

for analytics, send `proof` event via CLI

feat: add proof tracking event for analytics

---

clients/cli/src/config.rs

the CLI was not properly sending analytics event.
There were two issues:
1. depending on the websocket string a different firebase key is used, this had the wrong key <--- main issue
2. `analytics_api_key`function returned empty string in debug mode <--- minor issue

fix: CLI analytics fix

---

public/install.sh

Land this PR once email verification is re-enabled.
This reverts commit 7f8c088727c0ff78d515f1b9fe41c031ea46897e.

revert: "skip email verification"

---

README.md

**This PR** updates the **README.md** file to include the `protoc` (Protocol Buffers compiler) package as a prerequisite for Linux systems. The addition ensures that users do not encounter build errors related to missing protoc during the Nexus CLI installation process.
**Changes Made**:
Added `protobuf-compiler` to the apt install command under the Linux prerequisites section.
Why This Change is Needed:
The installation process for the Nexus CLI depends on protoc for building components.
Without this dependency, users may encounter errors like `Failed to run protoc: No such file or directory.`

Add protoc to prerequisites in README.md

---

public/install.sh

move mkdir to top, so it can save the prover id
to prevent creation of new prover-id
sh: 39: cannot create /home/username/.nexus/prover-id: Directory nonexistent
Warning: Could not read prover-id file: No such file or directory (os error 2)
Successfully saved new prover-id to file: favored-plantocracies-92

Move mkdir to top of install.sh

---

clients/cli/src/connection.rs

Update the logging in the CLI if it cannot connect to the backend:
New logging:
After 5 attempts it tells the user it has pinged Nexus

feat: update error logging

---

.github/workflows/ci.yml
clients/cli/Cargo.lock
clients/cli/Cargo.toml
clients/cli/build.rs

This PR addresses: [https://github.com/nexus-xyz/network-api/issues/55](https://github.com/nexus-xyz/network-api/issues/55).
The CLI requires `protoc` to be installed in user's computer to run. However, the protobuf files are already in the repo, so this is actually unnecessary.
1. Updates `build.rs` so it checks for the  previously generated protobuf files... so it does not block on if `protoc` is missing.
2. Updates the CI file so it does not install protoc
3. Updates the `cargo.toml` so it does not use prost-build (which requires protoc be installed)
1. Bumps the version number
1. I removed `protoc` from my computer
2. I tested so that:
```sh
$ protoc --version
> zsh: command not found: protoc
```
3. I ran the `cargo run` to make sure that the app still built and ran <-- this passes as …

feat: protoc should not be required

---

tests/test_updater.sh

The word "timee" contains a typo. The correct spelling is "**time**".

fix Update test_updater.sh

---

.github/ISSUE_TEMPLATE/bug_report.md
.github/ISSUE_TEMPLATE/config.yml

Some updates to the initial template

docs: issue template fixes

---

clients/cli/src/prover.rs
proto/orchestrator.proto

Changes:
1. clients/cli/src/prover.rs:
- "succesfully" -> "successfully"
2. proto/orchestrator.proto:
- "A open" -> "An open"
Reason:
Fixed spelling of "successfully" and corrected grammar article usage before vowel sound ("an" before "open").
Impact:
Documentation-only changes, no code functionality affected.

Fix spelling and grammar issues

---

proto/orchestrator.proto

There is a typo in the comment for `NETWORK_DEVNET` (line 75):  
- **"A open 'playground'"**  
It should be **"An open 'playground'"**, as "open" begins with a vowel sound.

typo fix Update orchestrator.proto

---

clients/cli/Cargo.lock
clients/cli/Cargo.toml
clients/cli/src/main.rs
clients/cli/src/memory_stats.rs
clients/cli/src/orchestrator_client.rs

Add memory and flops stats to NodeTelemetry

---

clients/cli/Cargo.lock
clients/cli/Cargo.toml
clients/cli/src/main.rs
clients/cli/src/orchestrator_client.rs
clients/cli/src/prover.rs
clients/cli/src/utils/cli_branding.rs

this PR addresses issue with CLI fetching inputs from orchestrator

fix: CLI fetch inputs

---

clients/cli/src/analytics.rs
clients/cli/src/orchestrator_client.rs
clients/cli/src/prover.rs
clients/cli/src/utils/cli_branding.rs

feat: increase CLI speed and speed analytics

---

clients/cli/build.rs

This PR fixes the Protobuf compilation issue where protoc fails due to proto3 optional fields not being explicitly allowed. 
Error message was :` Error compiling protobuf files: protoc failed: orchestrator.proto: This file contains proto3 optional fields, but --experimental_allow_proto3_optional was not set.` 
**Changes Made:**
1. Updated the build.rs file to add config.protoc_arg("--experimental_allow_proto3_optional");
2. Ensured that the correct .proto files are compiled without errors.
3. Verified that protoc runs successfully and generates the required Rust files.
**Why This Fix?**
1. Newer .proto files use optional fields in proto3, which require the --experimental_allow_proto3_optional flag to be set explicitly.
2. Without this fix, developers cloning the repo and trying to build …

Enabling proto3_optional flag

---

clients/cli/Cargo.lock
clients/cli/Cargo.toml
clients/cli/src/config.rs
clients/cli/src/orchestrator_client.rs
clients/cli/src/utils/cli_branding.rs

Orchestrator API path is changing, so update version number and path to match.
Clients that encounter 4xx errors will need to update.

chore!: Update API version

---

clients/cli/Cargo.lock
clients/cli/Cargo.toml
clients/cli/src/prover.rs
clients/cli/src/setup.rs
clients/cli/src/utils/cli_branding.rs

- Detect version automatically.
- Default to using the node id.
- Ensure that proving log statements are visible by default. (They were info-level. If we default to info-level, we could change this back.)

fix: logging, default to authenticated proving, automatic version

---

clients/cli/src/orchestrator_client.rs

Submit requests are typically processed in approximately 1 second. Based on the obtained data and conducted tests, the time is typically greater than the configured client timeout. Increasing the timeout will significantly improve the success rate of submits.

Increased client timeout

---

CONTRIBUTING.md
clients/cli/Cargo.toml
clients/cli/build.rs

- Update build.rs to skip compilation unless `--features build_proto` is set.
- Update docs

feat: don’t require protoc

---

clients/cli/src/utils/updater.rs
public/install.sh

Reason: Rustdoc uses /// for documentation comments that should be included in API documentation. The incorrect use of // prevented proper documentation parsing.
Reason: The closing parenthesis should be on the same line to maintain the correct structure, even within a commented-out section.

Fixing Documentation Comment and Formatting Issues

---

public/install.sh

Noticed that in section (6) *Clone or update the network-api repository*, the script runs `git stash` but doesn’t follow up with `git pull` or `git rebase`, leaving the local copy outdated.
Added the missing step to ensure the repository actually updates.

fix: fix missing pull/rebase after stash in network-api update

---

.github/workflows/release.yml

Build precompiled builds on CI and upload the artifacts. This has to land separately from the other changes to test with the workflow trigger.
Downloading precompiled builds will be added in https://github.com/nexus-xyz/network-api/pull/1474 and this change was reviewed there.

ci: Precompiled builds release trigger

---

clients/cli/Cargo.lock
clients/cli/Cargo.toml
clients/cli/src/orchestrator_client.rs
clients/cli/src/prover.rs

Postcard is a #![no_std] focused serializer and deserializer for Serde, and is used for proof serialization in the nexus-zkvm project.  
Fixes https://linear.app/nexus-labs/issue/NET-1033/update-cli-to-latest-release-of-nexus-zkvm

chore: Updates nexus-zkvm to a stable release, serializes proofs with postcard

---

CONTRIBUTING.md
README.md
clients/cli/Cargo.lock
clients/cli/Cargo.toml
clients/cli/README.md
clients/cli/src/utils/updater.rs
public/install.sh

- docs: Repo name changed to focus more on CLI
- chore: Update installer to use new repo name

chore: renaming network-api to nexus-cli

---

README.md

noticed the line "No prebuilt binaries yet." felt a bit abrupt, so I reworded it to "Prebuilt binaries are not yet available." - reads a bit smoother and keeps the meaning intact.

docs: clarified phrasing in "Current Limitations" section

---

clients/cli/src/config.rs

This is the default port exposed by the orchestrator.

chore: Use localhost:50505 for local proving

---

clients/cli/Cargo.lock
clients/cli/Cargo.toml
clients/cli/src/flops.rs
clients/cli/src/orchestrator_client.rs
clients/cli/src/prover.rs

The end result is the same and `available_parallelism` is available since version `1.59`.

chore: Replace `num_cpus` with `available_parallelism`

---

.github/workflows/release.yml

Replaced deprecated `softprops/action-gh-release@v1` with `softprops/action-gh-release@v2`
(latest stable v2.2.2) to receive ongoing fixes and features.
[Referance](https://github.com/softprops/action-gh-release/releases/tag/v2.2.2)

chore(ci): upgrade action-gh-release to v2

---

clients/cli/src/setup.rs

Don't ask the user if they want to use the existing config when `NONINTERACTIVE=1` is set

fix: Use existing config by default when `NONINTERACTIVE=1` is set

---

.github/workflows/release.yml
clients/cli/.dockerignore
clients/cli/Dockerfile
clients/cli/README.md

Adds a job to the Github release workflow to build and push the CLI's Docker image to Docker Hub.
- Multi-architecture Build for amd64 and arm64. (This is pretty slow...)
- Tags with latest, github SHA, and git tag
Fixes: https://linear.app/nexus-labs/issue/NET-1193/cli-release-workflow-for-docker-image

ci: Adds job to build and push Docker image

---

.github/workflows/firebase-hosting-release.yml

The firebase-hosting-release workflow is triggered by manual releases, but is not triggered when a release is created by the  release.yml workflow (e.g., when a tag is pushed). This allows the firebase-hosting-release.yml workflow to be manually triggered

ci: Add workflow_dispatch to Firebase hosting release workflow

---

clients/cli/README.md
public/install.sh

Highlight that the node ID must currently be set as a command-line argument

docs: Adds --node-id to README and installation script instruction

---

clients/cli/Cargo.lock
clients/cli/Cargo.toml
clients/cli/src/main.rs
clients/cli/src/orchestrator/mod.rs
clients/cli/src/prover.rs
clients/cli/src/prover_runtime.rs
clients/cli/src/ui/dashboard.rs
clients/cli/src/ui/mod.rs

Previously, each worker thread queried the Orchestrator directly for new tasks, leading to "429 Too many requests" errors.
This introduces a single background task that queries the Orchestrator and enqueues tasks for the provers. This task uses the newer API to request existing tasks, and requests that new tasks be assigned as needed.
Fixes: https://linear.app/nexus-labs/issue/NET-1266/cli-efficiently-manage-cli-orchestrator-messages
Fixes: https://linear.app/nexus-labs/issue/NET-1239/cli-prover-threads-should-consume-from-a-task-queue
TODO

feat: Worker threads consume from a central task queue

---

clients/cli/Cargo.lock
clients/cli/Cargo.toml
clients/cli/src/main.rs
clients/cli/src/prover_runtime.rs
clients/cli/src/ui/dashboard.rs
clients/cli/src/ui/mod.rs

Starting the CLI with the --headless flag disables the Terminal UI and prints log messages.
Sample output:
```
% cargo run -r start --node-id=5880437 --headless
Compiling nexus-network v0.8.5 (/Users/mfaulk/projects/network-api/clients/cli)
warning: nexus-network@0.8.5: Skipping proto compilation. Enable with `cargo clean && cargo build --features build_proto`
Finished `release` profile [optimized] target(s) in 5.37s
Running `target/release/nexus-network start --node-id=5880437 --headless`
Refresh [2025-06-12 16:06:12] Task Fetcher: Fetched 50 tasks
Success [2025-06-12 16:06:13] Prover 0: Proof completed successfully (Prover 0)
Refresh [2025-06-12 16:06:13] Task Fetcher: Fetched 50 tasks
Error [2025-06-12 16:06:14] Proof Submitter: Failed to submit proof for task 259407338623676441. …
```

feat: Adds "--headless" flag to Start command for running without the Terminal UI

---

clients/cli/src/orchestrator/client.rs
clients/cli/src/prover.rs

Fixes https://linear.app/nexus-labs/issue/NET-1429/cli-malformed-task-failed-to-parse-public-input-invalid-digit-found-in
Before:
```
Error [2025-06-17 14:37:57] Prover 2: Error: Malformed task: Failed to parse public input: invalid digit found in string
```
After:

fix: Fixes parsing of fibonacci task input

---

clients/cli/src/main.rs

Configures the number of prover workers based on the --max-threads command line argument. The number of workers is currently clamped to between 1 and 8 to avoid potential issues with backend rate limiting.
Fixes https://linear.app/nexus-labs/issue/NET-1424/cli-re-enable-multithreading

fix: Sets num_workers by clamping max_threads argument

---

clients/cli/src/config.rs
clients/cli/src/main.rs

Makes config file parsing backwards-compatible with older config file format containing a single "node_id" field.
Adds error handling to `start` command, and fails with an error message if a config file exists but cannot be read.
Fixes https://linear.app/nexus-labs/issue/NET-1459/cli-start-command-doesnt-read-node-id-from-configjson

feat: Should parse older config.json file containing only a node_id field

---

clients/cli/src/main.rs

Cleanly shuts down worker threads on Ctrl+C when in headless mode. A better main loop significantly reduces CPU usage in headless mode.
Some people have reported that the app doesn't always terminate (quickly?) on Ctrl+C. With this change, the CLI immediately reports "Exiting..." and waits for threads to shut down:
```
Refresh [2025-06-20 17:09:57] Task Fetcher: Fetched 50 tasks
Success [2025-06-20 17:10:00] Prover 0: Proof completed successfully (Prover 0)
^C
Exiting...
Nexus CLI application exited successfully.
```
Fixes https://linear.app/nexus-labs/issue/NET-1479/cli-should-shut-down-worker-threads-on-ctrlc

fix: Better thread shutdown for headless mode

---

clients/cli/src/prover_runtime.rs
clients/cli/src/task_cache.rs

Fixes https://linear.app/nexus-labs/issue/NET-1494/cli-404-failed-to-submit-proof-for-task
Updates the task fetcher to ignore task IDs that have recently been added to the task queue. Previously, task IDs would be ignored if they had been previously completed (i.e., successfully submitted), but it was possible to enqueue a task more than once before it was submitted for the first time. After a successful submission, the orchestrator would delete the task, and following attempts to submit the task failed with 404 task not found.

fix: fixes 404 "Failed to submit proof for task" by checking if tasks have already been equeued for processing

---

clients/cli/src/ui/dashboard.rs

Adds a "Starting..." message to the Dashboard logs. This gives an immediate indication of progress during the first couple of seconds while the CLI fetches initial tasks and processes them. The "Starting..." message disappears when the first log messages arrive
Fixes https://linear.app/nexus-labs/issue/NET-1550/cli-dashboard-logs-should-initialize-with-a-starting-message

ui:LOGS displays "Starting..." if the event log is empty

---

clients/cli/src/prover_runtime.rs

The task fetcher aggressively queries for the list of tasks assigned to a node. This is unnecessary, makes the UI noisy ("Fetched 50 tasks"), and may trigger rate limits.
https://github.com/nexus-xyz/nexus-cli/issues/1607
Fixes https://linear.app/nexus-labs/issue/NET-1541/cli-reduce-frequency-for-fetching-all-tasks

fix:Increases get_tasks interval from 1s to 3s

---

clients/cli/src/main.rs
clients/cli/src/orchestrator/error.rs
clients/cli/src/pretty.rs
clients/cli/src/register.rs

This PR pretty prints errors with coloring in stdout and references to raw error information being available on stderr.
So eg, at the moment you get something like:
This is both redundant and hard to see. Now, you should see something like 
And the bottom raw print out can be suppressed by sending `stderr` to `/dev/null` as normal.

Pretty Print Errors

---

clients/cli/src/workers/online.rs

The `online.rs` worker was using its own `TASK_QUEUE_SIZE` constant (set to 50), while the actual queue in `prover_runtime.rs` was initialized with a capacity of 100.
The core issue was in the queue calculation: `tasks_in_queue = 50 - 100`. This resulted in an integer underflow, making `tasks_in_queue` a massive number.

fix: Correct mismatched TASK_QUEUE_SIZE constant in online.rs

---

clients/cli/Cargo.lock
clients/cli/Cargo.toml

Many of the 0.8.x releases are incompatible with current orchestrator backend, so updating the major version to reflect the need to update.

chore: update to 0.9.0

---

clients/cli/Cargo.lock
clients/cli/Cargo.toml
clients/cli/src/main.rs

We used to persist a UUID to disk to uniquely identify the install of the CLI.
Now we use the node id, or "anonymous"

feat: use node id for analytics

---

clients/cli/src/task_cache.rs

Fixed a small inefficiency in the TaskCache implementation where we were checking for task ID existence twice - once in the `contains()` method and again in the `insert()` method after acquiring the mutex. This creates unnecessary mutex contention.

fix: optimize TaskCache.insert() by reusing contains() check while preserving pruning

---

clients/cli/src/environment.rs
tests/test_updater.sh

In order to successfully migrate our backend to using Ingress, we need to port the CLI client to production.orchestrator.nexus.xyz, which internally points to the Ingress controller. This requires changes to the ORCHESTRATOR_URL that the client uses.

feat: point CLI clients to production.orchestrator

---

.github/workflows/firebase-hosting-pull-request.yml
.github/workflows/firebase-hosting-release.yml
.gitignore
public/install.sh.template

How it works:
1. On release tag push → Firebase workflow triggers
2. Workflow extracts tag and generates platform-specific URLs
3. Template placeholders get replaced with real URLs
4. Generated install.sh gets deployed to Firebase
5. Users get a fast, reliable install script with hardcoded URLs
The install script now directly uses the correct URLs for each platform without any runtime API calls or JSON parsing.

Auto generate URL for latest release

---

proto/orchestrator.proto

The `GetProof-Task-Request` message contained a field named `ed25519PublicKey`, which used camelCase instead of the standard snake_case convention for Protobuf fields.
This commit renames the field to `ed25519_public_key` to align with the [Google Protobuf style guide](https://protobuf.dev/programming-guides/style/#message-and-field-names).

fix(proto): Correct field name and comment in GetProofTaskRequest

---

clients/cli/src/analytics.rs
clients/cli/src/prover.rs
clients/cli/src/workers/offline.rs
clients/cli/src/workers/online.rs

Make analytics functions truly non-blocking with tokio::spawn
Previously, analytics functions were commented as "non-blocking" but were
actually blocking the main execution flow by using .await, which waited
for HTTP requests to complete before continuing.
Changes:
- Update analytics function signatures to take owned values instead of references
- Use tokio::spawn at all call sites for fire-and-forget analytics
- Apply consistent pattern across `prover.rs`, `workers/online.rs`, and `workers/offline.rs`
Benefits:
- Proof verification and submission now happen at full speed
- Analytics HTTP requests run in background without delaying core functionality
- Failed analytics requests no longer impact prover reliability
- Comments now match actual non-blocking implementation
This ensures …

Make analytics functions truly non-blocking with `tokio::spawn`

---

clients/cli/src/environment.rs

eliminates unnecessary string cloning in the orchestrator_url() method by returning string references instead of owned strings. This improves performance by avoiding memory allocations, especially in code paths where this method is called
frequently. The method is used in critical network request paths, so this optimization can have a positive impact on overall CLI performance

refactor(environment): optimize orchestrator_url() to return &str instead of String

---

clients/cli/src/main.rs
clients/cli/src/pretty.rs
clients/cli/src/register.rs

- Add step-by-step guidance in start command that shows only the next required action
- Update register_user to display next step guidance after successful registration
- Update register_node to display next step guidance after successful registration
- Replace all println! with print_cmd_info! for consistent user message formatting
Users now get a smooth progressive experience:
1. Run 'nexus-cli start' → guided to register wallet
2. Run 'nexus-cli register-user' → guided to register node
3. Run 'nexus-cli register-node' → guided to start proving
4. Run 'nexus-cli start' → begins proving automatically
This eliminates confusion by showing only one step at a time instead of overwhelming users with all steps upfront.

Add progressive guided onboarding flow

---

clients/cli/build.rs
clients/cli/src/orchestrator/client.rs

All orchestrator API calls now include:
User-Agent: nexus-cli/{version} (e.g., nexus-cli/0.10.1)
- Add BUILD_TIMESTAMP constant using env! macro
- Set build timestamp in milliseconds since epoch during build process
- Add `X-Build-Timestamp` header to all HTTP requests:
* GET requests (get_request)
* POST requests (post_request)
* POST requests without response (post_request_no_response)
- Build timestamp is set in build.rs using SystemTime::now()
- Header value is in milliseconds since Unix epoch
Content-Type: application/octet-stream (for POST requests)
Pre-existing

feat: X-Build-Timestamp and User-Agent headers for orchestrator requests

---

clients/cli/src/main.rs
clients/cli/src/version_requirements.rs

If Firebase cannot be reached during version checking, try GitHub.
Update error link to go to the new issue page.

feat: Add fallback version.json

---

clients/cli/src/workers/online.rs

This PR upgrades the 
> [Task step 1 of 3]
message so that it's visible alongside the `2 of 3` and `3 of 3` messages with default settings..

chore: Repair Step Messaging

---

clients/cli/scripts/README.md
clients/cli/scripts/peak_memory.sh

Summary:
```
❯ ./peak_memory.sh 20
Starting nexus-network and monitoring memory for 20 seconds...
[1/20s] Current: 4 MB, Peak: 4 MB
[INFO!!!] ✅ Found Node ID from config file      Node ID:
Refresh [2025-07-31 08:09:24] Task Fetcher: [Task step 1 of 3] Fetching task... Note: CLI tasks are harder to solve, so they receive more points than web provers
Refresh [2025-07-31 08:09:24] Task Fetcher: Queue status: +1 task → 1 total (1% full)
[2/20s] Current: 241 MB, Peak: 241 MB
[3/20s] Current: 795 MB, Peak: 795 MB
[4/20s] Current: 1154 MB, Peak: 1154 MB
[5/20s] Current: 1993 MB, Peak: 1993 MB
[6/20s] Current: 2148 MB, Peak: 2148 MB
[7/20s] Current: 1097 MB, Peak: 2148 MB
[8/20s] Current: 994 MB, Peak: 2148 MB
[9/20s] Current: 1366 MB, Peak: 2148 MB
[10/20s] Current: 1433 MB, Peak: 2148 MB …
```

Add script to measure peak memory usage

---

clients/cli/src/workers/online.rs

The subsequent code has already checked whether headers["retry-after"] is empty or has a value and logged it. The logging here seems unnecessary and this code can be removed.
https://github.com/nexus-xyz/nexus-cli/blob/8aeba0087d93e0908175c017557e4aec8d32ecf4/clients/cli/src/workers/online.rs#L435-L454

headers["retry-after"] is empty and an error will occur

---

clients/cli/src/system.rs

fix: memory GB calculation

---

clients/cli/src/main.rs
clients/cli/src/orchestrator/client.rs
clients/cli/src/orchestrator/mod.rs
clients/cli/src/proto/nexus.orchestrator.rs
clients/cli/src/prover.rs
clients/cli/src/task.rs
clients/cli/src/version_checker.rs
clients/cli/src/workers/offline.rs
clients/cli/src/workers/online.rs
proto/orchestrator.proto

Handle a new task type that includes all the proof hashes instead of just a combined one.
This is to give the server more insight into why clients are submitting invalid proofs.

feat: new task type that includes all the proof hashes for multi-input proof

---

public/version.json

Update version.json to recommend 0.10.8
This doesn't require a release.

chore: recommend 0.10.8

---

clients/cli/src/analytics.rs

Use production rather than staging URL for reporting proving.
Staging and production basically do the same thing so no release is necessary.

fix: update report proving url

---

README.md
clients/cli/src/main.rs

Based on community feedback, this PR makes two (related) UX changes:
- adds a deprecation warning to the `--max-threads` parameter. We'll work on more officially removing/replacing that functionality, but for now we should mark that it is _not expected_  to do anything; and
- documents the `--headless` parameter for background/parallel usage of the CLI.

chore: Minor UX Improvements 

---

clients/cli/programs/fib_input_initial/src/main.rs

- Corrected spelling error in `clients/cli/programs/fib_input_initial/src/main.rs`
- Changed `seralized` to `serialized`

docs: fix typo in comment

---

clients/cli/src/ui/dashboard/components/metrics.rs

Corrected spelling error in metrics.rs TODO comment where `pointsq` should be `points`

docs: fix TODO comment: correct pointsq to points

---

.github/workflows/release.yml

Choose safer defaults for precompiled builds
Cargo checks for flags in a specific order, with later sources overriding earlier ones: 
- CARGO_ENCODED_RUSTFLAGS environment variable
- RUSTFLAGS environment variable
- target.<target-triple>.rustflags configuration entries
- build.rustflags configuration value

ci: compile architecture overrides
